### PR TITLE
fix: # escaping didn't work

### PR DESCRIPTION
**Pull request by saithis**
Somehow I missed that in my last PR :/

### CODE REVIEW

**Comment by jeffijoe** [comment]
Thanks! I'll merge and push a patch release when I'm back on my Windows machine. :)

I meant to ask, what do you think about the codebase? 😄

**Comment by saithis** [comment]
My impression of the codebase is mostly good. The code looks clean, the exception details are quite good and above all it works. The only thing is, that the code is maybe more complex than neccessary.

I have a prototype written in typescript which supports selectordinal, select, plural and variables and is (without interfaces) 260 lines of code. But that is without any error handling and the code is a bit messy. I just wrote it on an evening to get a better understanding for messageformat. 

It only has 2 complex parsing methods. One text parsing method and one for case arguments. The parsing returns Tokens with type text, var, num or func (func can have child tokens). This gets cached. For every translate call it iterates over the tokens and builds the string from them.

I havent explored it further, if it would work in a clean implemention with proper error handling and I don't know if it is that easy in C#, but that could be something worth looking into.

If you want, I can share the code with you.

**Comment by jeffijoe** [comment]
Cool! I am actually writing my own statically typed language in TypeScript and my parsing code is literally years ahead of whats in here. MessageFormat.NET was my first attempt at writing a parser, so I could probably do it cleaner if I were to rewrite it.

TypeScript is a bit easier to work with compared to C# though.

One thing I would change is have text be tokens as well. The `FormatRequest` is technically a glorified token, hehe. 😄

**Comment by saithis** [comment]
For a first attempt the result is quite good :)

Yes, Typescript is definitelly easier to work with. If you are interessted, I uploaded my messageformat prototype code here: [https://gitlab.com/snippets/1732080](https://gitlab.com/snippets/1732080)

**Comment by jeffijoe** [comment]
Merged and released as 3.0.1, thanks!

**Pull request merged**
